name: toy-dog-rl
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - mujoco
    - gymnasium
    - stable-baselines3[extra]
    - tensorboard
    - onnx
    - onnxruntime
    - jax[cuda12]
    - mujoco-mjx
    - flax
    - optax
